### PR TITLE
Add typechecking for insert!

### LINKED ISSUE #66: Add type check for `insert!`
`insert!` just inserts a program at a `NodeLoc`, but does not check for the feasibility of the inserted type.

### PR DESCRIPTION
**Pull request by nicolaefilat**
This pull request add typechecking when calling `insert`.
If trying to `insert` a subtree in a place where the wrong type is expected an error in thrown. 

For this check the grammar is also needed as an extra argument. This, however, breaks HerbSearch for now.
I will create a PR for HerbSearch soon.

This should close #66.

### CODE REVIEW

**Comment by ReubenJ** [comment]
This breaks tests in `HerbSearch`, by the way. Maybe this is intended, but can you take a look to confirm?

<details><summary>To reproduce errors</summary>
<p>

```julia
using Pkg

Pkg.activate(; temp=true)

packages = [
    PackageSpec(name="HerbConstraints", rev="dev"),
    PackageSpec(name="HerbGrammar", rev="add-typechecking-for-insert!"),
    PackageSpec(name="HerbCore", rev="dev"),
    PackageSpec(name="HerbInterpret", rev="dev"),
    PackageSpec(name="HerbSearch", rev="dev"), 
    PackageSpec(name="HerbSpecification", rev="dev")
]
Pkg.add(packages)

Pkg.test("HerbSearch")  # test only the HerbSearch package instead of all packages
```

</p>
</details>

**Comment by nicolaefilat** [comment]
Yes it breaks because it adds an extra field to the cross_over function. 
I have a fix ready for HerbSearch too but I did not make a PR for that.

**Comment by ReubenJ** [comment]
> I have a fix ready for HerbSearch too but I did not make a PR for that.

Would you mind posting a PR for that?

**Comment by ReubenJ** [comment]
@nicolaefilat I'm sorry, but I've lost track of whether that PR for `HerbSearch` has already been posted and/or merged. Can you confirm, and if not, post one when you can?

**Pull request closed without merging**
